[versions]
agp = "9.0.0"
kotlin = "2.2.10"
kotlinSerialization = "2.2.10"
ksp = "2.2.10-2.0.2"
compose-compiler = "1.5.10"
room = "2.8.4"
kotlinxSerializationJson = "1.10.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerialization" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
